### ISSUE TITLE
scatter.js attempts to only adjust fluorescence and scattering data for IFCB2, but does it for all data

### ISSUE THREAD

**Issue by joefutrelle** [LouisK130/oii#2]
Old-style data is any data with pids that begin "IFCB". This includes IFCB2, but also the rest of IFCB1 through IFCB9.

However scatter.js attempts the adjustment for new-style data as well, because of what looks like a typo in this expression:

```
 if(bin_pid.indexOf("/IFCB2"))
```

which to fix both problems I think should read

```
if(bin_pid.indexOf("/IFCB") != -1)
```

**Comment by LouisK130** [comment]
Thanks, the typo was my mistake. I was also unaware that old data could have different numbers for the suffix; it was my understanding it was just IFCB2.

I've adjusted that line as well as removed the client-side adjustments of columns.
